apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: webhook
    eventName: windspear
  triggers:
  - template:
      name: windspear
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: windspear-
              labels:
                app: windspear
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args:
                - "This is the ref you sent me:\n"
                - ""
                - "\nThis is the commit hash:\n"
                - ""
                - "\nThis is the repo address:\n"
                - ""
              - name: publish
                image: core.harbor.domain/digitalforge/windspear:0.1.26
                command: ["python"]
                env:
                - name: GITHOST
                  value: http://gitea-http.gitea:3000/
                - name: APIHOST
                  value: http://sysmlv2api.sysmlapi:9000/
                - name: SQLHOST
                  value: postgres-postgresql.windstorm:5432
                - name: HARBORTOOL
                  value: Harbor
                - name: ARTIFACTSTOOL
                  value: Artifacts
                args:
                - "src/main.py"
                - ""
                - ""
                - ""
                - ""
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.ref
            dest: spec.containers.0.args.1
          - src:
              dependencyName: payload
              dataKey: body.commits.0.id
            dest: spec.containers.0.args.3
          - src:
              dependencyName: payload
              dataKey: body.repository.full_name
            dest: spec.containers.0.args.5
          - src:
              dependencyName: payload
              dataKey: body.ref
            dest: spec.containers.1.args.1
          - src:
              dependencyName: payload
              dataKey: body.commits.0.id
            dest: spec.containers.1.args.2
          - src:
              dependencyName: payload
              dataKey: body.repository.full_name
            dest: spec.containers.1.args.3
          - src:
              dependencyName: payload
              dataKey: body.repository.default_branch
            dest: spec.containers.1.args.4
